### PR TITLE
Add normalising of battery level

### PR DESCRIPTION
**Pull request by joshxg**
Normalising the battery level (something about Blue maestro sensors showing the voltage between 75-100 or something?)

put some utils methods of ble service into utilservice and then made it a dependency

### CODE REVIEW

**Comment by mark-prins** [comment]
legend! I was thinking to do this one - but you've done it better.
The thought I had last night was how to share this change with mobile, will have a look at options when I'm done with the current backlog.

**Comment by joshxg** [comment]
Yes it's a tricky one.

I was thinking we likely would need to have some strategy pattern to construct manufacturer specific devices and then this utility might need to be used within that as this would break for laird sensors, for example

**Comment by joshxg** [comment]
oops I forgot to submit my self review

**Comment by mark-prins** [comment]
I suggest changing the battery icon though.
Currently the icon always shows more capacity than the numerical value. 
e.g. when my battery is 52% the icon shows 75%:

battery status


I'd recommend shifting the boundaries, so that they are still covering 25% but are centred around the battery percentage, rather than showing over the  value  ( this in `Battery.tsx` )
```
  const getIconProps = (level: number, charging: boolean): [ICON_NAME, COLOUR] => {
    if (charging) return [ICON_NAME.BATTERY_CHARGING, COLOUR.PRIMARY];
    if (level < 15) return [ICON_NAME.BATTERY_EMPTY, COLOUR.DANGER];
    if (level < 40) return [ICON_NAME.BATTERY_ONE, COLOUR.DANGER];
    if (level < 65) return [ICON_NAME.BATTERY_TWO, COLOUR.PRIMARY];
    if (level < 90) return [ICON_NAME.BATTERY_THREE, COLOUR.PRIMARY];
    return [ICON_NAME.BATTERY_FOUR, COLOUR.PRIMARY];
  };
```

**Comment by joshxg** [comment]
ah that's great, thanks! 
b20ec44

**Comment by mark-prins** [comment]
Still having issues.
It was showing an adjusted value on adding a sensor, but would soon after that 'refresh' and display the raw value.
Now, when I add a sensor I get this, which is arguably worse:

battery-start

**Comment by joshxg** [comment]
@mark-prins 

thanks- this covers the observer resetting the battery level
429539b

This covers the null in the settings 
8af52cd

**Review by mark-prins — APPROVED** [review]
wicked! 👍

**Pull request merged**
