### PR TITLE
Get android 11 to work

### PR DESCRIPTION
**Pull request by joshxg**
.. 🤷 

Something about OkHttp version mismatching... https://github.com/facebook/react-native/issues/28481

### CODE REVIEW

**Comment by joshxg** [comment]
Maybe should remove the code rather than comment it out..? Thought it was super useful for me to use while debugging mSupply integration issues, so would like to be able to easily enable it!

Anyway, this gets it to work on my android 11 emulator..

**Review by mark-prins — APPROVED** [review]
🎉  That does it for me 😄

**Comment by chetstone** [comment]
This works on my Samsung Tab A7 with Android 11. Thanks!

**Comment by joshxg** [comment]
Great!

**Pull request merged**
