### PR TITLE
#207 Add permission request to allow Android 10 export

### LINKED ISSUE #207: Export logs are not saved to device in Android 10
**Describe the bug**
Sensor export logs are not saved to the device when using Android 10 (Lenovo). 

Seems to work ok on Android 11 (Samsung): 

https://user-images.githubusercontent.com/19318937/139776006-445a42da-9f2d-424e-ad3e-33d82782a779.mp4

**To Reproduce**
1. Click into a sensor
2. Press the export button
3. Go try to find the exported file

**Expected behavior**
File to appear in the location indicated by the toast

**Smartphone (please complete the following information):**
 - Device: Lenovo X505N
 - OS: Android 10
 - Version 0.4.1-rc2

**Additional context**
This is causing issues for Cook Islands (also using Lenovo Android 10)

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #207 

As per PR title.

Tested on Lenovo M10 with Android 10 (didn't work before PR change but did after).
On Android 8.1 and 11 it worked even without this update (did a sanity test on Android 11 and still works with this PR change included).

### CODE REVIEW

**Review by joshxg — APPROVED** [review]
you're the best

**Comment by Chris-Petty** [comment]
Just a thought- does the orange screen of doom need to pop up for this permission, or is that just for the location/bluetooth, not storage?

**Comment by katherine-sussol** [comment]
> Just a thought- does the orange screen of doom need to pop up for this permission, or is that just for the location/bluetooth, not storage?

Hmm, it does currently pop up if it's not granted, although I'm not 100% sure whether it should (it doesn't technically stop the app from being usable - can still set up and collect data...but it's way less useful not being able to export 🤔 ).

**Comment by Chris-Petty** [comment]
Ya leave it in sounds good!

**Pull request merged**
